# Generated by Django 3.2.7 on 2021-11-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
