# Generated by Django 3.2.7 on 2021-12-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_picture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
    ]
